name: Test composite workflow
description: 'Test composite workflow'
inputs:
  CUSTOM_TAG:
    required: false
    type: string
    default: ''

runs:
  using: composite
  steps:
    - name: Pipeline Inputs
      shell: bash
      run: |
          echo "release_type: ${{ inputs.CUSTOM_TAG }}"
