name: On push
on:
  push:
    branches:
      - development
  workflow_dispatch:
    inputs:
      custom_tag:
        description: Custom version
        required: false
        type: string
        default: dev

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Pipeline Inputs
        if: ${{ inputs.custom_tag == '' }}
        id: snapshot_pom_version
        run: |
          echo "release_type: ${{ inputs.custom_tag }}"
      - name: Pipeline Inputs on condition
        id: snapshot_pom_version
        if: ${{ inputs.custom_tag != '' }}
        run: |
          echo "tag: ${{ inputs.custom_tag }}"
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Test composite workflow
        uses: ./.github/workflows/action/custom-workflow
        with:
          CUSTOM_TAG: ${{ inputs.custom_tag }}
