name: Create PR
on:
  workflow_dispatch:
    inputs:
      custom_tag:
        description: Custom tag
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Get initial pom version
        uses: avides/actions-project-version-check@v1.3.0
        id: initial_pom_version
        with:
          only-return-version: true
          file-to-check: pom.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Check if SNAPSHOT version exists
        id: check_snapshot_version
        shell: bash
        run: |
          if [ ${{ steps.initial_pom_version.outputs.version }} == *-SNAPSHOT* ]; then
            is_exists=true
          else
            is_exists=false
          fi
          echo "::set-output name=snapshot_exists::$is_exists"
          echo "$is_exists"
