name: On push
on:
  push:
    branches:
      - development
  workflow_dispatch:
    inputs:
      custom_tag:
        description: Custom version
        required: false
        type: string
        default: dev

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Pipeline Inputs
        run: |
          echo "release_type: ${{ inputs.custom_tag }}"
      - name: set tag
        id: github_tag
        run: |
          echo "::set-output name=new_tag::dummy"

      - name: Set target version
        id: target_version
        run: |
          if [ "${{ inputs.custom-tag }}" == "" ]; then
            target_tag: "${{ steps.github_tag.outputs.new_tag }}-SNAPSHOT"
          else
            target_tag: "${{ inputs.custom-tag }}"
          fi
          echo "::set-output name=version::$target_tag"
      - name: Target version
        run: |
          echo "target version: ${{ steps.target_version.outputs.version }}"
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Test composite workflow
        uses: ./.github/workflows/action/custom-workflow
        with:
          CUSTOM_TAG: ${{ inputs.custom_tag }}
