name: Create PR
on:
  workflow_dispatch:
    inputs:
      custom_tag:
        description: Custom tag
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          ref: release/2.1.0

      - name: Create PR
        run: gh pr create -B test-tagging -H release/2.1.0 --title 'Update application version to 2.2.0-SNAPSHOT' --body 'Update application version to 2.2.0-SNAPSHOT'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
